plugins:
  - uses:
      - plugin: "https://ubiquity-os-plugin-demo-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
        with:
          model: "anthropic/claude-3.5-sonnet"
          openAiBaseUrl: "https://openrouter.ai/api/v1"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev"
        skipBotEvents: false
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@main"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: "nXPQ-hjCdCGz_33dNvqwnyxzxW-88Bz4ycSfYs3OkA9ppU9j0yn6XaIuVtpyCdJnpS33c0IqKvI2i4ht54U-J_7M1UNUsRtId9XmgWXOeeJ2td7JMM9NtKLSp_dY9EUP8wAEKfGE5Gi3uKUV4H25x9zaReixtB9EYKbx3vtgGMUjYSq0"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-merging@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
